version: "3.8"

services:
  backend:
    container_name: usersnack
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - database
  

  database:
    image: postgres
    volumes:
      -  postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: usersnack_psgdb
    ports:
      - 5432:5432


volumes:
  postgres_data: